name: play_with_dart
description: A sample web application
dependencies:
  browser: any
  angular: ">=1.0.0 <2.0.0"
transformers:
- angular:
    html_files:
        - lib/component/recipe_book.html
        - lib/component/rating.html